export const types = {
  GET_DATA_SUCCESS: '[auth] GET_DATA_SUCCESS',
  GET_DATA_FAILURE: '[auth] GET_DATA_FAILURE',
  LOGOUT: '[auth] LOGOUT',
  GET_DOCUMENTS: '[documents] GET_DOCUMENTS',
  GET_DOCUMENT_SUCCESS: '[documents] GET_DOCUMENT_SUCCESS',
  GET_SELECTED_USER: 'GET_SELECTED_USER',
  UPDATE_DOCUMENT_SUCCESS: '[documents] UPDATE_DOCUMENT_SUCCESS',
  UPDATE_PASSWORD_SUCCESS: '[auth] UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILURE: '[auth] UPDATE_PASSWORD_FAILURE',
  SET_CURRENT_PATH: '[auth] SET_CURRENT_PATH',
  SET_LOADING_USERS: '[loading] SET_LOADING_USERS',
  SET_LOADING_ALERTS: '[loading] SET_LOADING_ALERTS',
  SET_LOADING_USER_DETAILS: '[loading] SET_LOADING_USER_DETAILS',
  SET_LOADING_DOCUMENT_TYPES: '[loading] SET LOADING DOCUMENT TYPES',
  SET_LOADING_DOCUMENT_CATEGORIES: '[loading] SET_LOADING_DOCUMENT_CATEGORIES'
};
